// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxhOEDx4KsFt1XFrdXx8Tr9T0dlEKTg4k',
    appId: '1:491698267080:web:403af0ae9e392a2ade96fd',
    messagingSenderId: '491698267080',
    projectId: 'fir-flutter-codelab-3c59c',
    authDomain: 'fir-flutter-codelab-3c59c.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-3c59c.appspot.com',
    measurementId: 'G-VWDSKDJERT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8LpY_aUI3nebJy7cQbHgXrg_spCuz4GM',
    appId: '1:491698267080:android:202a218582c00542de96fd',
    messagingSenderId: '491698267080',
    projectId: 'fir-flutter-codelab-3c59c',
    storageBucket: 'fir-flutter-codelab-3c59c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHuoclKB0bP_6YVeQCrybCpgpXCl09b9o',
    appId: '1:491698267080:ios:182f5a821ec54f60de96fd',
    messagingSenderId: '491698267080',
    projectId: 'fir-flutter-codelab-3c59c',
    storageBucket: 'fir-flutter-codelab-3c59c.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHuoclKB0bP_6YVeQCrybCpgpXCl09b9o',
    appId: '1:491698267080:ios:7feca47a81dccf6bde96fd',
    messagingSenderId: '491698267080',
    projectId: 'fir-flutter-codelab-3c59c',
    storageBucket: 'fir-flutter-codelab-3c59c.appspot.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
